language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r20-linux.tgz
  - tar -zxf android-sdk_r20-linux.tgz
  - export ANDROID_HOME=~/builds/avh4/uilayer/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter tools,platform-tools,android-10 --no-ui --force
